add_newline = false

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[➜](bold red) '

[line_break]
disabled = true

[username]
show_always = true

[nodejs]
disabled = true

[directory]
truncate_to_repo = true
truncation_length = 12

[package]
symbol = ""
